config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'public/users/registrations',
    sessions: 'public/users/sessions'
  }
  devise_scope :user do
   end
  devise_for :shops, path: 'shop', controllers: {
    registrations: 'shop/shops/registrations',
    sessions: 'shop/shops/sessions'
  }
  devise_for :admins, path: 'admin', controllers: {
    registrations: 'admin/admins/registrations',
    sessions: 'admin/admins/sessions'
  }
  scope module: :public do
    root 'home#top'
    resources :menus, only: [:show, :index] do
      resources :comments, only: [:create]
    end
    resources :shops, only: [:show, :index] do
      resources :reviews, only: [:create]
    end
    resources :reviews, only: [:update]
    post 'guest_login', to: "users#guest_login"
    resources :users, only: [:edit, :update, :destroy]
  end
  namespace :shop do
    root 'menus#index'
    resources :shops, only: [:show, :edit, :update, :destroy]
    resources :menus
    resources :comments, only: [:create, :destroy]
  end
  namespace :admin do
    root to: "users#index"
    resources :users, only: [:index, :show, :destroy]
    resources :reviews, only: [:index, :destroy]
    resources :comments, only: [:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :shop
  has_one_attached :image
  
  validates :name, presence: true
  enum category: { food: 0, drink: 1, beer: 2 }
  
  has_many :comments, dependent: :destroy
end

app/models/shop.rb
class Shop < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :image
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
         #:recoverable, 
         
  has_many :menus, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :ball_park
end

app/controllers/shop/home_controller.rb
class Shop::HomeController < ApplicationController
  def top

  end
end

app/controllers/shop/menus_controller.rb
class Shop::MenusController < ApplicationController
  before_action :authenticate_shop!
  
  def new
    @menu = Menu.new  
  end
  
  def create
    @menu = current_shop.menus.build(menu_params)
    if @menu.save
      flash[:notice] = "success"
      redirect_to shop_menus_path
    else
      flash.now[:alert] = "failed"
      render :new
    end
  end

  def index
     @menus = current_shop.menus
  end

  def show
    @menu = Menu.find(params[:id])  
  end

  def edit
    @menu = Menu.find(params[:id])
  end
  
  def update
    @menu = Menu.find(params[:id])
    if @menu.update(menu_params)
      flash[:notice] = "succes"
      redirect_to shop_menu_path(@menu)
    else
      flash.now[:alert] = "failed"
      render :edit
    end
  end
  
  def destroy
    menu = Menu.find(params[:id]) 
    menu.destroy
    redirect_to shop_menus_path
  end
  
  private
  def menu_params
    params.require(:menu).permit(:name, :price, :category, :comment, :image)
  end
end

app/controllers/shop/shops/confirmations_controller.rb
# frozen_string_literal: true

class Shop::Shops::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/shop/shops/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Shop::Shops::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/shop/shops/passwords_controller.rb
# frozen_string_literal: true

class Shop::Shops::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/shop/shops/registrations_controller.rb
# frozen_string_literal: true

class Shop::Shops::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone, :ball_park_id])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/shop/shops/sessions_controller.rb
# frozen_string_literal: true

class Shop::Shops::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/shop/shops/unlocks_controller.rb
# frozen_string_literal: true

class Shop::Shops::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/shop/shops_controller.rb
class Shop::ShopsController < ApplicationController
  before_action :authenticate_shop!
  before_action :correct_user
  
  def show
    
  end
  
  def edit
  end
  
  def update
    if @shop.update(shop_params)
      flash[:notice] = "success"
      redirect_to shop_shop_path(@shop)
    else
      flash.now[:alert] = "failed"
      render :edit
    end
  end
  
  def destroy
    @shop.destroy
    flash[:notice] = "success"
    redirect_to root_path
  end
  
  public
  
  def shop_params
    params.require(:shop).permit(:name)
  end
  
  def correct_user
    @shop = Shop.find_by_id(params[:id])
    redirect_to shop_root_url unless current_shop == @shop
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/shop/home_helper.rb
module Shop::HomeHelper
end

app/views/shop/menus/_form.html.erb
 <%= render 'layouts/error_messages', model: f.object %>

  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*", class: "form-control" %>

  <h4>商品名</h4>
  <%= f.text_field :name, class: "form-control" %>
  
  <h4>価格</h4>
  <%= f.text_field :price, class: "form-control" %>
  
  <h4>カテゴリ</h4>
  <%= f.select :category, Menu.categories.keys, {}, { class: "form-control" } %>
	
  <h4>コメント</h4>
  <%= f.text_area :comment, class: "form-control" %>

app/views/shop/menus/_menus.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>商品名</th>
      <th>価格</th>
      <th>カテゴリ</th>
      <th>コメント</th>
    </tr>
  </thead>
  <tbody>
    <% menus.each do |menu| %>
      <tr>
        <% if current_shop %>
          <td><%= link_to menu.name, shop_menu_path(menu) %></td>
        <% else %>
          <td><%= link_to menu.name, menu_path(menu) %></td>
        <% end %>
        <td><%= menu.price %></td>
        <td><%= menu.category %></td>
        <td><%= menu.comment.truncate(20) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shop/menus/edit.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2 col-lg-6 offset-lg-3">
    <h1>メニュー編集</h1>
    <%= form_with model: @menu, url: shop_menu_path(@menu) do |f| %>
      <%= render 'form', f: f %>
    	
      <%= f.submit '投稿', class: "btn btn-primary mt-4" %>
    <% end %>
  </div>
</div>

app/views/shop/menus/index.html.erb
<h1>メニュー一覧</h1>

<%= render 'shop/menus/menus', menus: @menus %>

<% if current_shop %>
  <%= link_to "new_menu", new_shop_menu_path, class: "btn btn-primary" %>
<% end %>

app/views/shop/menus/new.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2 col-lg-6 offset-lg-3">
    <h1>新規メニュー作成</h1>
    <%= form_with model: @menu, url: shop_menus_path do |f| %>
      <%= render 'form', f: f %>
    	
      <%= f.submit '投稿', class: "btn btn-primary mt-4" %>
    <% end %>
  </div>
</div>

app/views/shop/menus/show.html.erb
<h1>メニュー詳細</h1>

<table class="table table-bordered">
  <tbody>
    <tr>
      <th>商品名</th>
      <td><%= @menu.name %></td>
    </tr>    
    <tr>
      <th>価格</th>
      <td><%= @menu.price %></td>
    </tr>
    <tr>
      <th>カテゴリ</th>
      <td><%= @menu.category %></td>
    </tr>
    <tr>
      <th>コメント</th>
      <td><%= @menu.comment %></td>
    </tr>
    <tr>
      <th>画像</th>
      <td>
        <% if @menu.image.attached? %>
          <%= image_tag @menu.image, size: "200x200" %>
        <% else %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<% if current_shop && current_shop == @menu.shop %>
  <%= link_to "編集", edit_shop_menu_path(@menu.id), class: "btn btn-warning" %>
  <%= link_to "削除", shop_menu_path(@menu.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %>
<% end %>

<div class="row">
  <div class="col-md-7">
    <h2>コメント一覧</h2>
    <table class="table">
      <tbody>
        <% @menu.comments.each do |comment| %>
          <tr>
            <td><%= comment.content %></td>
            <td><%= l comment.created_at, format: :short %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% if current_user %>
    <div class="col-md-5">
      <h2>コメントを書く</h2>
      <%= form_with model: @comment, url: menu_comments_path(@menu) do |f| %>
        <%= f.label :content %>
        <%= f.text_area :content, rows: 5, class: "form-control" %> 
        <%= f.submit "comment", class: "btn btn-primary mt-2" %> 
      <% end %>
    </div>
  <% end %>
</div>

<% if current_shop %>
  <%= link_to "メニュー一覧へ", shop_menus_path, class: "btn btn-secondary" %>
<% else %>
  <%= link_to "全メニューを見る", menus_path, class: "btn btn-secondary" %>
  <%= link_to "shop詳細へ", shop_path(@menu.shop), class: "btn btn-secondary" %>
<% end %>