config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'public/users/registrations',
    sessions: 'public/users/sessions'
  }
  devise_scope :user do
   end
  devise_for :shops, path: 'shop', controllers: {
    registrations: 'shop/shops/registrations',
    sessions: 'shop/shops/sessions'
  }
  devise_for :admins, path: 'admin', controllers: {
    registrations: 'admin/admins/registrations',
    sessions: 'admin/admins/sessions'
  }
  scope module: :public do
    root 'home#top'
    resources :menus, only: [:show, :index] do
      resources :comments, only: [:create]
    end
    resources :shops, only: [:show, :index] do
      resources :reviews, only: [:create]
    end
    resources :reviews, only: [:update]
    post 'guest_login', to: "users#guest_login"
    resources :users, only: [:edit, :update, :destroy]
  end
  namespace :shop do
    root 'menus#index'
    resources :shops, only: [:show, :edit, :update, :destroy]
    resources :menus
    resources :comments, only: [:create, :destroy]
  end
  namespace :admin do
    root to: "users#index"
    resources :users, only: [:index, :show, :destroy]
    resources :reviews, only: [:index, :destroy]
    resources :comments, only: [:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :image
  devise :database_authenticatable,
         :rememberable, :validatable
         #:recoverable, :registerable,
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ball_park.rb
class BallPark < ApplicationRecord
  has_many :shops
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :menu
  
  validates :content, presence: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :shop
  has_one_attached :image
  
  validates :name, presence: true
  enum category: { food: 0, drink: 1, beer: 2 }
  
  has_many :comments, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

app/models/shop.rb
class Shop < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :image
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
         #:recoverable, 
         
  has_many :menus, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :ball_park
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :image
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
         #:recoverable, 
         
  validates :name, presence: true
         
  has_many :comments, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.all
    if params[:keyword].present?
      @users = @users.where('id LIKE ?', "%#{params[:keyword]}%").or(
               @users.where('name LIKE ?', "%#{params[:keyword]}%")).or(
               @users.where('email LIKE ?', "%#{params[:keyword]}%"))
    end
  end

  def show
    @user = User.find(params[:id])
    @comments = @user.comments
    @reviews = @user.reviews
  end
  
  def destroy
    @user = User.find_by_id(params[:id])
    @user&.destroy
    flash[:notice] = "削除しました"
    redirect_to admin_users_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shop/home_controller.rb
class Shop::HomeController < ApplicationController
  def top

  end
end

app/controllers/shop/menus_controller.rb
class Shop::MenusController < ApplicationController
  before_action :authenticate_shop!
  
  def new
    @menu = Menu.new  
  end
  
  def create
    @menu = current_shop.menus.build(menu_params)
    if @menu.save
      flash[:notice] = "success"
      redirect_to shop_menus_path
    else
      flash.now[:alert] = "failed"
      render :new
    end
  end

  def index
     @menus = current_shop.menus
  end

  def show
    @menu = Menu.find(params[:id])  
  end

  def edit
    @menu = Menu.find(params[:id])
  end
  
  def update
    @menu = Menu.find(params[:id])
    if @menu.update(menu_params)
      flash[:notice] = "succes"
      redirect_to shop_menu_path(@menu)
    else
      flash.now[:alert] = "failed"
      render :edit
    end
  end
  
  def destroy
    menu = Menu.find(params[:id]) 
    menu.destroy
    redirect_to shop_menus_path
  end
  
  private
  def menu_params
    params.require(:menu).permit(:name, :price, :category, :comment, :image)
  end
end

app/controllers/shop/shops_controller.rb
class Shop::ShopsController < ApplicationController
  before_action :authenticate_shop!
  before_action :correct_user
  
  def show
    
  end
  
  def edit
  end
  
  def update
    if @shop.update(shop_params)
      flash[:notice] = "success"
      redirect_to shop_shop_path(@shop)
    else
      flash.now[:alert] = "failed"
      render :edit
    end
  end
  
  def destroy
    @shop.destroy
    flash[:notice] = "success"
    redirect_to root_path
  end
  
  public
  
  def shop_params
    params.require(:shop).permit(:name)
  end
  
  def correct_user
    @shop = Shop.find_by_id(params[:id])
    redirect_to shop_root_url unless current_shop == @shop
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/shop/home_helper.rb
module Shop::HomeHelper
end

app/views/admin/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/admin/shared/_search_form.html.erb
<div class="row my-4">
  <div class="col-md-10">
    <%= form_with url: url, method: :get do |f| %>
      <div class="row">
        <div class="col-md-5">
          <%= f.search_field :keyword, class: "form-control", value: params[:keyword], placeholder: "キーワードで検索" %>
        </div>
        <div class="col-md-2">
          <%= f.submit "search", class: "btn btn-primary btn-block" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <ul>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if notice %>
  <div class="alert alert-success my-3">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger my-3">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <% if current_admin %>
      <a class="navbar-brand" href="/admin">スタグルコンソール</a>
    <% elsif current_shop %>
      <a class="navbar-brand" href="/shop">スタグル</a>
    <% else %>
      <a class="navbar-brand" href="/">スタグル</a>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item mr-5">
            <span class="nav-link"><%= current_user.name %>さんようこそ</span>
          </li>
          <li class="nav-item">
            <%= link_to "ユーザー情報の変更", edit_user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% elsif current_shop %>
          <li class="nav-item mr-5">
            <span class="nav-link"><%= current_shop.name %>さんようこそ</span>
          </li>
          <li class="nav-item">
            <%= link_to "新規メニュー作成", new_shop_menu_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "店舗詳細", shop_shop_path(current_shop), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_shop_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% elsif current_admin %>
          <li class="nav-item">
            <%= link_to "ユーザー一覧", admin_root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "レビュー一覧", admin_reviews_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "コメント一覧", admin_comments_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "管理者ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "ユーザーログイン", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ユーザー新規登録", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "出店者ログイン", new_shop_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "出店者新規登録", new_shop_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ゲストログイン", guest_login_path, method: :post, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StaGour</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= yield(:bg_area) %>
    <div class="container">
      <%= render "layouts/flash_messages" %>
      <%= yield %>
    </div>
    <% if Rails.env.development? %>
      <%= debug params %>
      admin:<%= current_admin.inspect %><br>
      shop:<%= current_shop.inspect %><br>
      user:<%= current_user.inspect %>
    <% end %>
  </body>
</html>